steps:
  - id: "Deploy Workflows"
    name: "gcr.io/cloud-builders/gcloud:latest"
    entrypoint: /bin/bash
    allowFailure: true
    args:
      - "-c"
      - |
        . /workspace/tools/runTest.sh
        for src in $(find ./src/ -type f -name *.workflows.yaml); do
          runTest $src &
        done
        wait

  - id: "Check for Errors"
    name: "gcr.io/cloud-builders/gcloud:latest"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        if [ -f /workspace/failures.txt ]; then
            echo "Tests FAILED!"
            cat /workspace/failures.txt
            exit 1
        else 
            echo "Tests PASSED!"
        fi

substitutions:
  _REGION: us-central1
