steps:
  - id: "Get Changed Files"
    name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    entrypoint: bash
    args:
      - -exc
      - |
        apt-get update
        apt-get install jq -y

        curl -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/GoogleCloudPlatform/workflows-samples/pulls/$_PR_NUM/files \
          | jq '.[].filename' > /workspace/changed.txt

  - id: "Deploy Workflows"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: /bin/bash
    allowFailure: true
    args:
      - "-c"
      - |
        cat /workspace/changed.txt

        for src in $(echo /workspace/changed.txt | grep *.workflows.yaml); do
          echo $src
          tmp_name=${src:6}  # remove src/
          tmp_name=${tmp_name/connectors\//}  # remove connectors/ if present
          workflow_name=${tmp_name//./-}-$SHORT_SHA  # convert . to -

          test="$(gcloud workflows deploy $workflow_name \
            --source $src \
            --location $_REGION \
            --quiet 2>&1)"
          
          if [[ $? -ne 0 ]]; then
            echo "$workflow_name (src: $src) failed!" >> /workspace/failures.txt
            echo $test >> /workspace/failures.txt
          fi

          gcloud workflows delete $workflow_name \
            --location $_REGION \
            --quiet
        done

  - id: "Check for Errors"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        if [ -f /workspace/failures.txt ]; then
            echo "Tests FAILED!"
            cat /workspace/failures.txt
            exit 1
        else 
            echo "Tests PASSED!"
        fi

substitutions:
  _REGION: us-central1
