name: Presubmit - E2E Test
on: [pull_request]
env:
  REGION: us-central1

jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.result }}
    steps:
    - name: Get changed files
      uses: actions/github-script@v6
      id: get-files
      with:
        script: |
          const resp = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{github.event.pull_request.number}}
          });
          const files = resp.data.map((file) => file.filename);
          return files.filter((filename) => filename.startsWith('src'));

  test:
    name: Run Workflows Test Matrix
    runs-on: ubuntu-latest
    needs: get
    if: ${{ needs.get.outputs.files != '[]' && needs.get.outputs.files != '' }}
    strategy:
      fail-fast: false
      matrix: 
        file: ${{ fromJSON(needs.get.outputs.files) }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - id: Authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ''
        service_account: ''
        create_credentials_file: true
        

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Deploy Workflow
      id: test
      run: |
        # Create a Workflow name based on the filename
        NAME=${{ matrix.file }}
        TMP_NAME=${NAME:4}  # remove src/
        TMP_NAME=${TMP_NAME/connectors\//}  # remove connectors/ if present
        WORKFLOW=${TMP_NAME//./-} #-${{ github.run_id }}  # convert . to -

        gcloud workflows deploy $WORKFLOW --source ${{ matrix.file }} --location $REGION --quiet
        echo "::set-output name=WORKFLOW::$WORKFLOW"

    - name: Clean up Workflow
      if: ${{ steps.test.outputs.WORKFLOW != '' }}
      run:
        gcloud workflows delete ${{ steps.test.outputs.WORKFLOW }} --location $REGION --quiet
