name: Validate Filename
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Validate Filenames
        run: ./validateFilenames.sh
