name: Validate Filename
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Validate Filenames
        run: ./validateFilenames.sh
