name: Validate Filename
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Validate Filenames
      run: ./validateFilenames.sh
