name: Generate JSON PR
on: 
  push: 
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install yamljs CLI
      run: npm install -g yamljs

    - name: Run toJSON script
      run: ./tojson.sh

    - name: Check for diff
      run: git diff --exit-code 

    - name: Create pull request for changes
      uses: 'peter-evans/create-pull-request@dcd5fd746d53dd8de555c0f10bca6c35628be47a'
      if: ${{ failure() }}
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        committer: 'yoshi-code-bot <yoshi-code-bot@google.com>'
        author: 'yoshi-code-bot <yoshi-code-bot@google.com>'
        signoff: 'yoshi-code-bot <yoshi-code-bot@google.com>'
        commit-message: 'chore: generate JSON'
        title: 'chore: generate JSON'
        body: 'AUTOMATED PR! This PR was created to regen/fix the JSON payloads.'
        base: 'main'
        branch: 'actions/build'
        add-paths: 'src/'
        push-to-fork: 'yoshi-code-bot/workflows-samples'
        delete-branch: true