name: Generate JSON PR
on: 
  push: 
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install yamljs CLI
      run: npm install -g yamljs

    - name: Run toJSON script
      run: ./tojson.sh

    - name: Check for diff
      run: git diff --exit-code
  
    - name: Create pull request for changes
      uses: googleapis/code-suggester@v3 # takes the changes from git directory
      if: ${{ failure() }} # run if diff exists
      env:
        ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }} # manually created and added as repo secret
      with:
        command: pr
        upstream_owner: ${{ github.repository_owner }}
        upstream_repo: 'workflows-samples'
        description: 'Generated in GitHub action: https://github.com/${{ github.repository }}/actions/workflows/generate_json_pr.yaml'
        title: 'chore: Regenerate JSON'
        message: 'chore: Regenerate JSON'
        branch: 'main'
        git_dir: 'src/'
        primary: 'main'
        force: true
        fork: true # action automatically forks repo
