name: Validate JSON
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install yamljs CLI
      run: npm install -g yamljs
    - name: Run toJSON script
      run: ./tojson.sh
    - name: Ensure there is no diff
      run: git diff --exit-code .