name: Generate JSON PR
on:
  push:
    branches: [main]
    paths-ignore:
      - "jsonschema/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install yamljs CLI
        run: npm install -g yamljs

      - name: Run toJSON script
        run: ./tools/tojson.sh

      - name: Create pull request for changes
        uses: googleapis/code-suggester@v4
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }} # manually created and added as repo secret
        with:
          command: pr
          upstream_owner: ${{ github.repository_owner }}
          upstream_repo: "workflows-samples"
          title: "chore: Regenerate JSON"
          message: "chore: Regenerate JSON"
          description: "Generated in GitHub action: https://github.com/${{ github.repository }}/actions/workflows/generate_json_pr.yaml"
          branch: "main"
          git_dir: "src/"
          primary: "main"
          force: true
          fork: true # action automatically forks repo
