name: Generate JSON PR
on: 
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install yamljs CLI
      run: npm install -g yamljs
    - name: Run toJSON script
      run: ./tojson.sh
    - name: Commit and create PR if needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # If there is a non-zero diff after running generator
        if [[ `git status --porcelain` ]]; then
          git config --global user.email "yoshi-code-bot@google.com"
          git config --global user.name "Google Bot"
          git checkout -b "pr_bot-$GITHUB_RUN_ID"
          git add -A
          NOW=$(date +"%m-%d-%Y")
          git commit --message "fix: generate JSON (${NOW})"
          git push origin "pr_bot-$GITHUB_RUN_ID"
          echo "Created commit: $(git rev-parse HEAD)"
          gh pr create \
            --title "fix: generate JSON (${NOW})" \
            --body "AUTOMATED PR! This PR was created to regen/fix the JSON payloads."
        else
          # No changes after running generator
          echo "No PR to create."
        fi