name: Validate Demo Syntax
on:
  pull_request:
    paths:
      - "jsonschema/workflows.json"

jobs:
  get-all-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-files.outputs.result }}
    steps:
      - name: workflows-demos > Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: GoogleCloudPlatform/workflows-demos
          path: workflows-demos

      - name: Get source files
        uses: actions/github-script@v6
        id: get-files
        with:
          script: |
            const fs = require('fs');
            const Path = require('path');
            const workspace = process.env.GITHUB_WORKSPACE;
            let getFiles = function (dir) {
              let dirents = fs.readdirSync(dir, { withFileTypes: true });
              return dirents.map((dirent) => dirent.isDirectory() ? 
                  getFiles(Path.join(dir, dirent.name)) : Path.join(dir, dirent.name)).flat();
            }
            return getFiles(".")
                .filter((filename) => filename.endsWith('yaml'));

  smoke-test:
    runs-on: ubuntu-latest
    needs: get-all-files
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.get-all-files.outputs.matrix) }}
    steps:
      - name: workflows-samples > Checkout Repository
        uses: actions/checkout@v3

      - name: workflows-demos > Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: GoogleCloudPlatform/workflows-demos
          path: workflows-demos

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Set up tooling
        run: npm install -g ajv-cli ajv-formats

      - name: Run Smoke Tests
        run: |
          ajv validate -c ajv-formats \
            -s jsonschema/workflows.json \
            -d ${{ matrix.sample }}
