name: Validate Sample Syntax
on:
  pull_request:
    paths:
      - "src/**"
      - "jsonschema/workflows.json"

jobs:
  get-all-files:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    outputs:
      matrix: ${{ steps.get-files.outputs.result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Get source files
        uses: actions/github-script@v6
        id: get-files
        with:
          script: |
            const fs = require('fs');
            const Path = require('path');
            const workspace = process.env.GITHUB_WORKSPACE;

            let files = fs.readdirSync(Path.join(workspace, 'src'))
                .map((file) => Path.join('./src', file));
            let connectors = fs.readdirSync(Path.join(workspace, 'src/connectors'))
                .map((file) => Path.join('./src/connectors', file));
            return files.concat(connectors)
                .filter((filename) => filename.endsWith('yaml') || filename.endsWith('json'));

  smoke-test:
    runs-on: ubuntu-latest
    needs: get-all-files
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.get-all-files.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install tools
        run: npm install -g ajv-cli ajv-formats

      - name: Validate sample syntax
        run: |
          ajv validate -c ajv-formats \
            -s jsonschema/workflows.json \
            -d ${{ matrix.sample }}
